config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :auto_completes, only: [] do
    collection do
      get :wiki_tags
      get :issue_tags
      get :all_tags
    end
  end

  resources :additional_tags, only: %i[index edit update] do
    collection do
      post :merge
      get :context_menu, :merge
      delete :destroy
    end
  end

  resource :issue_tags, only: %i[edit] do
    collection do
      post :update
    end
  end

  resources :projects, only: [] do
    resources :wiki, only: [], as: 'wiki_page' do
      member do
        put :update_tags
      end
    end
  end
end

app/controllers/issue_tags_controller.rb
# frozen_string_literal: true

class IssueTagsController < ApplicationController
  before_action :find_issues, only: %i[edit update]

  def edit
    return unless AdditionalTags.setting?(:active_issue_tags) &&
                  User.current.allowed_to?(:edit_issue_tags, @projects.first)

    @issue_ids = params[:ids]
    @is_bulk_editing = @issue_ids.size > 1
    @issue_tags = if @is_bulk_editing
                    issues = @issues.map(&:tag_list)
                    issues.flatten!
                    issues.uniq
                  else
                    @issues.first.tag_list
                  end

    @issue_tags.sort!
    @most_used_tags = Issue.available_tags.most_used 10
  end

  def update
    if AdditionalTags.setting?(:active_issue_tags) &&
       User.current.allowed_to?(:edit_issue_tags, @projects.first)
      tags = params[:issue] && params[:issue][:tag_list] ? params[:issue][:tag_list].reject(&:empty?) : []

      unless User.current.allowed_to?(:create_issue_tags, @projects.first) || Issue.allowed_tags?(tags)
        flash[:error] = t :notice_failed_to_add_tags
        return
      end

      Issue.transaction do
        @issues.each do |issue|
          issue.tag_list = tags
          issue.save!
        end
      end
      flash[:notice] = t :notice_tags_added
    else
      flash[:error] = t :notice_failed_to_add_tags
    end
  rescue StandardError => e
    Rails.logger.warn "Failed to add tags: #{e.inspect}"
    flash[:error] = t :notice_failed_to_add_tags
  ensure
    redirect_to_referer_or { render text: 'Tags updated.', layout: true }
  end
end

app/views/issue_tags/_edit_modal.html.slim
h3.title = l :label_add_tags

- if @is_bulk_editing
  h3 = l :label_bulk_edit_selected_issues
  ul
    - @issues.each do |issue|
      li = link_to_issue issue
- else
  h3
    span = link_to_issue @issues.first

= form_tag issue_tags_path(ids: @issue_ids, search: params[:search]) do
  fieldset.box
    legend = l :field_tags
    #issue_tags
      = additionals_select2_tag 'issue[tag_list]',
                                options_for_select(@issue_tags.map { |tag| [tag, tag] }, @issue_tags),
                                multiple: true,
                                style: 'width: 100%;',
                                url: issue_tags_auto_completes_path(project_id: @project),
                                placeholder: @is_bulk_editing ? t(:label_no_change_option) : '+ add tag',
                                tags: User.current.allowed_to?(:create_issue_tags, @project)
    p.most_used_tags
      = safe_join @most_used_tags.collect { |t| tag.span t.name, class: 'most_used_tag' }, ', '

  .buttons
    = submit_tag l(:button_add), name: nil
    '
    = link_to_function l(:button_cancel), 'hideModal(this);'

javascript:
  var mostUsedTags = #{raw @most_used_tags.map(&:name)};

app/views/issue_tags/edit.js.erb
$('#ajax-modal').html('<%= escape_javascript(render partial: 'issue_tags/edit_modal') %>');
showModal('ajax-modal', '600px');