config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :auto_completes, only: [] do
    collection do
      get :wiki_tags
      get :issue_tags
      get :all_tags
    end
  end

  resources :additional_tags, only: %i[index edit update] do
    collection do
      post :merge
      get :context_menu, :merge
      delete :destroy
    end
  end

  resource :issue_tags, only: %i[edit] do
    collection do
      post :update
    end
  end

  resources :projects, only: [] do
    resources :wiki, only: [], as: 'wiki_page' do
      member do
        put :update_tags
      end
    end
  end
end

app/views/wiki/_tags_form.html.slim
= additionals_select2_tag 'wiki_page[tag_list]',
                          options_for_select(@page.tag_list.map { |tag| [tag, tag] }, @page.tag_list),
                          multiple: true,
                          width: '95%',
                          url: wiki_tags_auto_completes_path(project_id: @project),
                          placeholder: l(:label_add_tags),
                          tags: true

app/views/wiki/_tags_form_bottom.html.slim
- if AdditionalTags.setting?(:active_wiki_tags) && User.current.allowed_to?(:add_wiki_tags, @project)
  p#wiki_tags
    = label_tag l(:field_tag_list)
    = render partial: 'wiki/tags_form',
             locals: { project: project, page: page }

app/views/wiki/_tags_show.html.slim
- if AdditionalTags.setting? :active_wiki_tags
  .wiki-attributes
    = render partial: 'additional_tags/tag_list',
             locals: { entry: page,
                       show_always: true,
                       link_wiki_tag: true,
                       editable: User.current.allowed_to?(:add_wiki_tags, @project),
                       update_url: update_tags_project_wiki_page_path(@project, page.title),
                       use_colors: AdditionalTags.setting?(:use_colors) }

app/views/wiki/_tags_sidebar.html.slim
- if AdditionalTags.setting?(:active_wiki_tags) && sidebar_tags.present?
  .sidebar-tags
    h3 = l :field_tags
    = render_sidebar_tags

app/views/wiki/tag_index.html.slim
.contextual
  - if User.current.allowed_to? :edit_wiki_pages, @project
    = link_to l(:label_wiki_page_new), new_project_wiki_page_path(@project), remote: true, class: 'icon icon-add'

h2 = render_wiki_index_title @project, @tag

- if @pages.empty?
  p.nodata = l :label_no_data
- else
  ul.wiki-tag-entries
    - @pages.each do |page|
      li
        = link_to page.pretty_title, project_wiki_page_path(@project, page.title)
        - if page.parent.present?
          p.parent
            = l :field_parent_title
            ' :
            = link_to page.parent.pretty_title, project_wiki_page_path(@project, page.parent.title)

- content_for :sidebar do
  = render partial: 'sidebar'